// Code generated by logcopter-gen; DO NOT EDIT.

package output_file

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var zlog = logcopter.Package("go-go-golems.parka.pkg.glazed.handlers.output-file")
