// Code generated by logcopter-gen; DO NOT EDIT.

package static_dir

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var zlog = logcopter.Package("go-go-golems.parka.pkg.handlers.static-dir")
