// Code generated by logcopter-gen; DO NOT EDIT.

package static_file

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var zlog = logcopter.Package("go-go-golems.parka.pkg.handlers.static-file")
