// Code generated by logcopter-gen; DO NOT EDIT.

package generic_command

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var zlog = logcopter.Package("go-go-golems.parka.pkg.handlers.generic-command")
