// Code generated by logcopter-gen; DO NOT EDIT.

package template_dir

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var zlog = logcopter.Package("go-go-golems.parka.pkg.handlers.template-dir")
